# Generated by Django 4.2.11 on 2024-04-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_billing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_active', 'Can active users')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
