# Generated by Django 4.2.11 on 2024-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_billing_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('TRANS', 'Перевод на счёт')], verbose_name='Способ оплаты'),
        ),
    ]
