# Generated by Django 4.2.11 on 2024-05-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_billing_link_billing_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='payday',
            field=models.DateTimeField(auto_created=True, blank=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('TRANS', 'Перевод на счёт')], default='TRANS', verbose_name='Способ оплаты'),
        ),
    ]
