# Generated by Django 4.2.11 on 2024-05-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_billing_payday_alter_billing_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='payday',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
