# Generated by Django 4.2.11 on 2024-06-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('pk',), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
